/**
 * Receipt Vault — Frontend Configuration Template
 *
 * DO NOT rename this file to config.js and commit it.
 * config.js is auto-generated by setup.sh and is gitignored.
 *
 * If you need to set this manually (e.g. for local dev):
 *   1. Copy this file to config.js
 *   2. Replace the API_URL with your Worker URL
 *   3. Do NOT commit config.js
 */
window.VAULT_CONFIG = {
  API_URL: 'https://YOUR_WORKER_NAME.YOUR_ACCOUNT.workers.dev',
}
